### ISSUE TITLE
Proxy to multiple endpoints

### ISSUE THREAD

**Issue by benzwjian** [wotcity/wotcity-wot-framework#26]
I'd like to add a feature of proxying data to multiple endpoints, for example of coap-proxy-websocket, proxying a coap data to 2 websocket brokers, then viewed by 2 websocket viewer respectively. My plan is to hold a relationship between **pathname**, **endpoint host** and **websocket connection** in Coap proxy server, likes this:
```javascript
proxyToWebsocketBrokers = {
  '/object/5550937980d51931b3000009/send': {
    'localhost:8000': wsConn1,
    'localhost:8001': wsConn2
  },
  '/object/6661234567d4444b1111111/send': {
    'localhost:8000': wsConn3,
    'localhost:8001': wsConn4
  }
}
```
where `wsConn1`, `wsConn2`, `wsConn3` and `wsConn4` are:
```javascript
var wsConn1 = wsClient.connect('ws://localhost:8000/object/5550937980d51931b3000009/send', '');
var wsConn2 = wsClient.connect('ws://localhost:8001/object/5550937980d51931b3000009/send', '');
var wsConn3 = wsClient.connect('ws://localhost:8000/object/6661234567d4444b1111111/send', '');
var wsConn4 = wsClient.connect('ws://localhost:8001/object/6661234567d4444b1111111/send', '');
```
Coap proxy server will keep the received coap data under specific pathname until a websocket connection established.

Any thoughts are welcome.

**Comment by jollen** [comment]
I tried #27 for a few days, and it is a wonderful use case.

**Comment by benzwjian** [comment]
Appreciate #27 merged.
